### ISSUE TITLE
Error while starting Geyser after compiling the source 

### ISSUE THREAD

**Issue by Mespeczek** [LoyaltyMC/Geyser#2]
![](https://cdn.discordapp.com/attachments/663050316807405578/680104098816721018/Screenshot_2020-02-20-18-29-46.png)
![](https://cdn.discordapp.com/attachments/663050316807405578/680104099244802050/Screenshot_2020-02-20-18-29-57.png)

**Comment by LegacyGamerHD** [comment]
try refreshing your config

**Comment by LegacyGamerHD** [comment]
some poeple reported that tm that that works

**Comment by Legit4K** [comment]
I think you forgot to update submodules; before compiling run ```git submodule update --init --recursive```

**Comment by Mespeczek** [comment]
Works! Thank you!
