### ISSUE TITLE
Ladders Not Working

### ISSUE THREAD

**Issue by ramdon-person** [LoyaltyMC/Geyser#3]
**Describe the bug**
you can not climb ladders from minecraft bedrock edition

**To Reproduce**
1. Join a floodgate server
2. attempt to climb a ladder

**Expected behavior**
you can climb the ladder

**Screenshots**

**Server version**
paper-90 (MC: 1.15.2)

**Geyser version**
Latest Compiled Version of LoyaltyMC

**Bedrock version**
1.14.0

**Additional context**

**Comment by LegacyGamerHD** [comment]
Geyser issue also seems to work for me
