### ISSUE TITLE
Chunk sometimes don't show up, just blank

### ISSUE THREAD

**Issue by AnonAlpha** [LoyaltyMC/Geyser#9]
**Describe the bug**
When player join they have a high rate to see all blank, or they can see the chunk they are standing in or other chunk. They have to reenter again and again to see it

**To Reproduce**
1. Use  the legecy branch and floodgate
2. Start the server
3. Join the game

**Expected behavior**
Chunk always get loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/55188112/76036797-10c4b180-5f80-11ea-9b3f-f54d297d498f.png)

**Server version**
1.15.2 spigot latest build

**Geyser version**
latest for legecy branch in action

**Bedrock version**
latest 1.14.3

**Comment by LegacyGamerHD** [comment]
Legacy is outdated you shouldn't use it anymore master will soon be updated

**Comment by LegacyGamerHD** [comment]
Also a geyser issue

**Comment by LegacyGamerHD** [comment]
there is pending fix for the issue https://github.com/GeyserMC/Geyser/pull/196

**Comment by AnonAlpha** [comment]
thanks
